/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const AMS: typeof import('@arco-design/web-vue')['MS']
  const API: typeof import('@arco-design/web-vue')['PI']
}
